'use client'
import {useState} from 'react'
import {useQuery,useMutation,useQueryClient,useInfiniteQuery} from '@tanstack/react-query'
import {BookOpen,FileText,Upload,Search,ShieldCheck,Layers,RefreshCw} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog'

type KB={id:string;name:string;description?:string|null;chunkCount:number;agentCount:number}
type Version={id:string;version_number:number;status:string;failure_code:string|null;chunk_count:number;indexed_at:string|null;source_sha256:string|null}
type Document={id:string;filename:string;enabled:boolean;current_version_id:string|null;latest_version:number;versions:Version[];currentVersion:Version|null}
type Hit={id:string;content:string;document_id:string;version_id:string;version_number:number;chunk_index:number;knowledgeBaseId:string}
type Retrieval={hits:Hit[];trace:{agentVersionId:string;mode:string;degraded:boolean;quarantinedChunkIds:string[]}}
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{const r=await fetch(path,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),json=await r.json();if(!r.ok)throw Error(json.error??'Request failed');return json}
function VersionHistory({document,kb}:{document:Document;kb:string}){
 const [open,setOpen]=useState(false)
 const history=useInfiniteQuery({queryKey:['knowledge-history',document.id,document.latest_version],enabled:open,initialPageParam:document.latest_version+1,queryFn:({pageParam})=>api<{data:Version[];nextBefore:number|null}>('/api/knowledge/'+kb+'/documents/'+document.id+'/versions?before='+pageParam),getNextPageParam:last=>last.nextBefore??undefined,initialData:{pages:[{data:document.versions,nextBefore:document.versions.length===20?document.versions[19].version_number:null}],pageParams:[document.latest_version+1]}})
 return <details className="mt-3 text-xs" onToggle={e=>setOpen(e.currentTarget.open)}><summary className="cursor-pointer text-muted-foreground">Version history ({document.latest_version})</summary><ol className="mt-3 space-y-2">{history.data.pages.flatMap(p=>p.data).map(v=><li key={v.id} className="break-words rounded-lg bg-muted/50 p-3">Version {v.version_number} · {v.status} · {v.chunk_count} chunks{v.indexed_at?' · '+new Date(v.indexed_at).toLocaleString():''}<span className="mt-1 block text-muted-foreground">Version reference: {v.id}</span></li>)}</ol>{history.error&&<p role="alert" className="mt-2 text-red-600">{history.error.message}</p>}{history.hasNextPage&&<Button className="mt-3" size="sm" variant="outline" disabled={history.isFetchingNextPage} onClick={()=>void history.fetchNextPage()}>Load older versions</Button>}</details>
}
const inputClass='min-w-0 w-full rounded-lg border bg-background p-2 text-sm'
export function KnowledgeWorkspace({knowledgeBaseId}:{knowledgeBaseId?:string}){
 const client=useQueryClient(),[selected,setSelected]=useState<string>(),[createOpen,setCreateOpen]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState(''),[file,setFile]=useState<File|null>(null),[replacement,setReplacement]=useState(''),[uploadKey,setUploadKey]=useState(0),[notice,setNotice]=useState(''),[error,setError]=useState(''),[remove,setRemove]=useState<Document|null>(null),[agentId,setAgentId]=useState(''),[query,setQuery]=useState(''),[retrieval,setRetrieval]=useState<Retrieval|null>(null)
 const auth=useQuery({queryKey:['knowledge-auth'],queryFn:()=>api<{data:{role:string}}>('/api/auth/me')})
 const canWrite=!!auth.data&&auth.data.data.role!=='viewer'
 const bases=useQuery({queryKey:['knowledge-bases'],queryFn:()=>api<{data:KB[]}>('/api/knowledge-bases')})
 const kbId=knowledgeBaseId??selected??bases.data?.data[0]?.id,kb=bases.data?.data.find(k=>k.id===kbId)
 const docs=useQuery({queryKey:['knowledge-documents',kbId],enabled:!!kbId,queryFn:()=>api<{data:Document[]}>('/api/knowledge/'+kbId+'/documents'),refetchInterval:state=>state.state.data?.data.some(d=>['queued','parsing','embedding'].includes(d.versions[0]?.status))?2000:false})
 const agents=useQuery({queryKey:['knowledge-preview-agents'],queryFn:()=>api<{data:{id:string;name:string;active:boolean;publishedVersionId?:string|null}[]}>('/api/agents')})
 const mutation=useMutation({mutationFn:async(action:{kind:string;document?:Document})=>{
  if(!canWrite)throw Error('Your role has read-only access')
  if(action.kind==='create'){if(!name.trim())throw Error('Enter a knowledge base name');return api('/api/knowledge-bases','POST',{name:name.trim(),description:description.trim(),sourceType:'document'})}
  if(action.kind==='upload'){
   if(!file)throw Error('Choose a document to upload');if(file.size===0||file.size>2*1024*1024)throw Error('Choose a document between 1 byte and 2 MB')
   if(!/\.(txt|md|json|pdf|docx)$/i.test(file.name))throw Error('Supported formats: PDF, DOCX, TXT, MD and JSON')
   const response=await fetch('/api/knowledge/'+kbId+'/documents'+(replacement?'/'+replacement+'/versions':''),{method:'POST',headers:{'content-type':'application/octet-stream','x-document-name':encodeURIComponent(file.name)},body:file}),data=await response.json();if(!response.ok)throw Error(data.error??'Upload failed');return data
  }
  const d=action.document!,path='/api/knowledge/'+kbId+'/documents/'+d.id
  if(action.kind==='reindex')return api(path+'/reindex','POST',{})
  if(action.kind==='remove')return api(path,'DELETE')
  return api(path,'PATCH',{enabled:!d.enabled})
 },onMutate:()=>{setError('');setNotice('')},onError:e=>setError(e.message),onSuccess:(_data,action)=>{setNotice(action.kind==='upload'||action.kind==='reindex'?'Document queued. Indexing progress appears below.':'Changes saved.');setRetrieval(null);if(action.kind==='create'){setCreateOpen(false);setName('');setDescription('')}if(action.kind==='upload'){setFile(null);setReplacement('');setUploadKey(k=>k+1)}if(action.kind==='remove')setRemove(null);void client.invalidateQueries({queryKey:['knowledge-documents']});void client.invalidateQueries({queryKey:['knowledge-bases']})}})
 const preview=useMutation({mutationFn:()=>api<{data:Retrieval}>('/api/knowledge/retrieval','POST',{query,agentId}),onMutate:()=>{setError('');setRetrieval(null)},onError:e=>setError(e.message),onSuccess:r=>setRetrieval(r.data)})
 const items=docs.data?.data??[],ready=items.filter(d=>d.enabled&&d.current_version_id).length,pending=items.filter(d=>['queued','parsing','embedding'].includes(d.versions[0]?.status)).length
 return <div className="min-w-0 space-y-6">
  <div className="flex flex-wrap items-start justify-between gap-4 rounded-2xl border bg-gradient-to-br from-background to-teal-50/50 p-6 dark:to-teal-950/20"><div className="min-w-0"><p className="mb-2 text-xs font-medium uppercase tracking-widest text-teal-700 dark:text-teal-400">Knowledge workspace</p><h1 className="flex items-center gap-2 text-2xl font-semibold"><BookOpen className="h-6 w-6 text-teal-600"/>Knowledge your team can trust</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">Upload documents, review their versions and control what your assistant can use.</p></div><Button disabled={!canWrite} onClick={()=>setCreateOpen(true)}>New knowledge base</Button></div>
  {auth.data?.data.role==='viewer'&&<p className="rounded-xl border p-3 text-sm">Read-only access. You can review documents and test retrieval.</p>}
  {(error||bases.error||docs.error||auth.error)&&<p role="alert" className="break-words rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:bg-red-950 dark:text-red-200">{error||bases.error?.message||docs.error?.message||auth.error?.message}</p>}
  {notice&&<p role="status" className="rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800 dark:bg-teal-950 dark:text-teal-200">{notice}</p>}
  {bases.isLoading?<p role="status">Loading knowledge bases…</p>:!bases.data?.data.length?<div className="rounded-2xl border border-dashed p-10 text-center"><BookOpen className="mx-auto mb-3 h-8 w-8 text-teal-600"/><h2 className="font-semibold">Start with your first knowledge base</h2><p className="mt-2 text-sm text-muted-foreground">Create a space for company guides, FAQs and reference documents.</p></div>:<>
   <div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(0,0.7fr)_minmax(0,2fr)]">
    <aside className="min-w-0 rounded-2xl border bg-card p-4"><h2 className="mb-3 font-semibold">Your knowledge bases</h2><div className="flex flex-col gap-2">{bases.data.data.map(base=><button key={base.id} aria-pressed={kbId===base.id} onClick={()=>{setSelected(base.id);setReplacement('');setRetrieval(null);setError('');setNotice('')}} disabled={!!knowledgeBaseId&&knowledgeBaseId!==base.id} className={'rounded-xl border p-3 text-start transition-colors '+(kbId===base.id?'border-teal-300 bg-teal-50 dark:bg-teal-950':'hover:bg-muted')}><span className="block break-words text-sm font-medium">{base.name}</span><span className="mt-1 block text-xs text-muted-foreground">{base.chunkCount} retained chunks · {base.agentCount} agents</span></button>)}</div></aside>
    <section className="min-w-0 space-y-4">
     <div className="flex flex-wrap gap-3">{[{label:'Available documents',value:ready,icon:ShieldCheck},{label:'Indexing',value:pending,icon:RefreshCw},{label:'Total documents',value:items.length,icon:Layers}].map(stat=><div key={stat.label} className="min-w-0 flex-1 rounded-xl border bg-card p-4"><stat.icon className="mb-2 h-4 w-4 text-teal-600"/><p className="text-2xl font-semibold">{stat.value}</p><p className="text-xs text-muted-foreground">{stat.label}</p></div>)}</div>
     <form onSubmit={e=>{e.preventDefault();mutation.mutate({kind:'upload'})}} className="rounded-2xl border bg-card p-5"><div className="mb-4 flex items-center gap-2"><Upload className="h-5 w-5 text-teal-600"/><h2 className="break-words font-semibold">Add to {kb?.name??'knowledge base'}</h2></div><div className="grid min-w-0 gap-4 sm:grid-cols-2"><label className="min-w-0 text-sm">Document<input key={uploadKey} type="file" accept=".pdf,.docx,.txt,.md,.json" disabled={!canWrite||mutation.isPending} onChange={e=>setFile(e.target.files?.[0]??null)} className="mt-2 block w-full min-w-0 rounded-lg border p-2 text-xs"/></label><label className="text-sm">Version target<select aria-label="Version target" value={replacement} onChange={e=>setReplacement(e.target.value)} disabled={!canWrite} className={'mt-2 '+inputClass}><option value="">New document</option>{items.map(d=><option key={d.id} value={d.id}>{d.filename}</option>)}</select></label></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">PDF, DOCX, TXT, MD or JSON · up to 2 MB{file?' · Unsaved selection':''}</p><Button disabled={!canWrite||!file||mutation.isPending}>{mutation.isPending?'Saving…':'Upload document'}</Button></div></form>
     <div className="rounded-2xl border bg-card p-5"><h2 className="mb-4 font-semibold">Documents</h2>{docs.isLoading?<p role="status">Loading documents…</p>:!items.length?<p className="rounded-xl border border-dashed p-6 text-sm text-muted-foreground">No documents yet. Upload a guide or FAQ to get started.</p>:<div className="max-h-[38rem] space-y-3 overflow-y-auto">{items.map(d=>{const latest=d.versions[0],current=d.currentVersion;return <article key={d.id} className="min-w-0 rounded-xl border p-4"><div className="flex flex-col items-start justify-between gap-3 sm:flex-row"><div className="w-full min-w-0 sm:flex-1"><h3 className="flex items-start gap-2 text-sm font-medium"><FileText className="h-4 w-4 shrink-0 text-teal-600"/><span className="min-w-0 flex-1 break-all">{d.filename}</span></h3><p className="mt-2 text-xs text-muted-foreground">{d.enabled?'Enabled':'Disabled'} · Latest version {latest?.version_number} · {latest?.status}</p>{current&&<p className="mt-1 text-xs text-muted-foreground">Available version {current.version_number} · {current.chunk_count} chunks</p>}{latest?.failure_code&&<p role="alert" className="mt-2 text-xs text-red-600">Indexing failed: {latest.failure_code.replaceAll('_',' ').toLowerCase()}. {current?'The previous indexed version is retained.':'This document is unavailable to the assistant.'} Retry indexing after correcting the source or service configuration.</p>}</div><div className="flex w-full flex-wrap gap-2 sm:w-auto"><Button size="sm" variant="outline" disabled={!canWrite||mutation.isPending} onClick={()=>mutation.mutate({kind:'toggle',document:d})}>{d.enabled?'Disable':'Enable'}</Button><Button size="sm" variant="outline" disabled={!canWrite||mutation.isPending||['queued','parsing','embedding'].includes(latest?.status)} onClick={()=>mutation.mutate({kind:'reindex',document:d})}>Reindex</Button><Button size="sm" variant="ghost" disabled={!canWrite||mutation.isPending} onClick={()=>setRemove(d)}>Delete</Button></div></div><VersionHistory document={d} kb={kbId!}/></article>})}</div>}</div>
    </section>
   </div>
   <section className="rounded-2xl border bg-card p-5"><h2 className="flex items-center gap-2 font-semibold"><Search className="h-4 w-4 text-teal-600"/>Test what your assistant can find</h2><p className="mt-2 text-sm text-muted-foreground">Uses the selected assistant&apos;s published knowledge permissions. Disabled and deleted documents are excluded.</p><form onSubmit={e=>{e.preventDefault();preview.mutate()}} className="mt-4 grid min-w-0 gap-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,2fr)_auto]"><label className="text-xs">Assistant<select aria-label="Assistant" value={agentId} onChange={e=>{setAgentId(e.target.value);setRetrieval(null)}} className={'mt-1 '+inputClass}><option value="">Select assistant</option>{agents.data?.data.filter(a=>a.active&&a.publishedVersionId).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="text-xs">Question<Input className="mt-1" value={query} onChange={e=>setQuery(e.target.value)} maxLength={2000} placeholder="Ask in English or Arabic"/></label><Button className="self-end" disabled={!agentId||!query.trim()||preview.isPending}>{preview.isPending?'Searching…':'Test retrieval'}</Button></form>{retrieval&&<div className="mt-4 space-y-3"><p role="status" className="text-sm">{retrieval.hits.length} supported excerpts found{retrieval.trace.degraded?' · Lexical fallback or partial retrieval; check embedding service configuration.':''}{retrieval.trace.quarantinedChunkIds.length?' · Unsafe document instructions were excluded.':''}</p>{retrieval.hits.map(hit=><div key={hit.id} className="min-w-0 rounded-xl border p-4"><p className="whitespace-pre-wrap break-words text-sm">{hit.content}</p><p className="mt-3 break-all text-xs text-muted-foreground">Knowledge base {hit.knowledgeBaseId} · Document {hit.document_id} · Version {hit.version_number} ({hit.version_id}) · Chunk {hit.chunk_index+1} ({hit.id})</p></div>)}</div>}</section>
  </>}
  <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>New knowledge base</DialogTitle><DialogDescription>Keep related company documents in one space.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();mutation.mutate({kind:'create'})}} className="space-y-4"><label className="block text-sm">Name<Input value={name} onChange={e=>setName(e.target.value)} maxLength={120} required className="mt-2"/></label><label className="block text-sm">Description<Input value={description} onChange={e=>setDescription(e.target.value)} maxLength={500} className="mt-2"/></label>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<Button disabled={!canWrite||mutation.isPending}>Create knowledge base</Button></form></DialogContent></Dialog>
  <Dialog open={!!remove} onOpenChange={open=>{if(!open)setRemove(null)}}><DialogContent><DialogHeader><DialogTitle>Delete document?</DialogTitle><DialogDescription>{remove?.filename} will stop appearing in future retrieval. Its version history is retained for recovery.</DialogDescription></DialogHeader><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setRemove(null)}>Cancel</Button><Button variant="destructive" disabled={mutation.isPending} onClick={()=>mutation.mutate({kind:'remove',document:remove!})}>Confirm deletion</Button></div>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}</DialogContent></Dialog>
 </div>
}
