'use client'
import { useState } from 'react'
import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query'
import { ArrowRightLeft,Check,Clock,ShieldCheck,UserRound } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { toast } from 'sonner'

type Member={id:string;name:string;active?:boolean;available?:boolean;working_hours?:{timezone:string;days:number[];start:string;end:string}|null}
type Conversation={id:string;handoff_state:string;assigned_to:string|null;handoff_reason?:string;handoff_due_at?:string}
type Detail={data:Conversation;teamMembers:Member[];events:{id:string;event_type:string;to_state:string;created_at:string}[];notifications:{id:string;status:string;failure_code:string|null}[]}
type Rule={id:string;name:string;team_member_id:string;areas:string[];priority:number}
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{const response=await fetch('/api/handoffs'+path,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw Error(result.error??'Handoff request failed');return result as T}
const stateLabel=(s:string)=>s.toLowerCase().replaceAll('_',' ')
function MemberSchedule({member,busy,onSave}:{member:Member;busy:boolean;onSave:(value:{member:Member;available:boolean;working_hours:Member['working_hours']})=>void}){
 const [enabled,setEnabled]=useState(Boolean(member.working_hours)),[zone,setZone]=useState(member.working_hours?.timezone??'UTC'),[days,setDays]=useState(member.working_hours?.days??[1,2,3,4,5]),[start,setStart]=useState(member.working_hours?.start??'09:00'),[end,setEnd]=useState(member.working_hours?.end??'18:00')
 return <details className="mt-2 rounded-xl border p-3"><summary className="cursor-pointer text-xs">Working hours for {member.name}</summary><form onSubmit={e=>{e.preventDefault();onSave({member,available:member.available!==false,working_hours:enabled?{timezone:zone,days,start,end}:null})}} className="mt-3 grid gap-3">
  <label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Limit assignments to working hours</label>
  {enabled&&<><label className="text-xs">Timezone<input required className="mt-1 block w-full rounded-lg border bg-background p-2 text-sm" value={zone} onChange={e=>setZone(e.target.value)} placeholder="Asia/Dubai"/></label><fieldset><legend className="mb-2 text-xs">Working days</legend><div className="flex flex-wrap gap-3">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,index)=><label key={day} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={days.includes(index)} onChange={e=>setDays(e.target.checked?[...days,index]:days.filter(d=>d!==index))}/>{day}</label>)}</div></fieldset><div className="grid grid-cols-2 gap-3"><label className="text-xs">Start<input required type="time" className="mt-1 block w-full min-w-0 rounded-lg border bg-background p-2" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-xs">End<input required type="time" className="mt-1 block w-full min-w-0 rounded-lg border bg-background p-2" value={end} onChange={e=>setEnd(e.target.value)}/></label></div></>}
  <Button size="sm" variant="outline" disabled={busy||(enabled&&!days.length)}>Save working hours</Button>
 </form></details>
}
export function HandoffControls({conversationId}:{conversationId:string}){
 const client=useQueryClient(),[agent,setAgent]=useState('')
 const query=useQuery({queryKey:['handoff',conversationId],queryFn:()=>api<Detail>('/'+conversationId),refetchInterval:10000})
 const action=useMutation({mutationFn:(value:{action:string;agentId?:string})=>api('/'+conversationId,'POST',value),onSuccess:()=>{void client.invalidateQueries({queryKey:['handoff']});void client.invalidateQueries({queryKey:['handoffs']});void client.invalidateQueries({queryKey:['conversation']});void client.invalidateQueries({queryKey:['conversations']})},onError:(e:Error)=>toast.error(e.message)})
 if(query.isLoading)return <p className="p-4 text-sm text-muted-foreground" role="status">Loading handoff…</p>
 if(!query.data)return <div className="p-4"><p role="alert" className="text-sm text-destructive">{query.error?.message??'Handoff unavailable'}</p><Button variant="outline" onClick={()=>void query.refetch()}>Retry</Button></div>
 const {data:c,teamMembers,events,notifications}=query.data,pending=['HANDOFF_REQUESTED','ASSIGNED','WAITING_FOR_AGENT'].includes(c.handoff_state)
 return <section aria-label="Conversation handoff" className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950">
  <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-teal-50 p-2 text-teal-700 dark:bg-teal-950"><ArrowRightLeft size={18}/></span><div><h3 className="font-medium">Human handoff</h3><p className="text-xs capitalize text-muted-foreground" role="status">{stateLabel(c.handoff_state)}</p></div></div><span className="flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1 text-xs dark:bg-slate-900"><ShieldCheck size={14}/>{c.handoff_state==='HUMAN_ACTIVE'||c.handoff_state==='RESOLVED'?'AI paused':'AI available'}</span></div>
  {c.assigned_to&&<p className="mt-3 text-sm">Assigned to {teamMembers.find(m=>m.id===c.assigned_to)?.name??'unavailable member'}</p>}
  {c.handoff_due_at&&<p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><Clock size={13}/>Response due {new Date(c.handoff_due_at).toLocaleTimeString()}</p>}
  <div className="mt-4 flex flex-wrap gap-2">
   {c.handoff_state==='AI_ACTIVE'&&<Button disabled={action.isPending} onClick={()=>action.mutate({action:'request'})}>Request human</Button>}
   {pending&&<><label className="sr-only" htmlFor={'handoff-agent-'+conversationId}>Assign team member</label><select id={'handoff-agent-'+conversationId} className="min-w-0 rounded-lg border bg-background px-3 py-2 text-sm" value={agent} onChange={e=>setAgent(e.target.value)}><option value="">Select team member</option>{teamMembers.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><Button variant="outline" disabled={!agent||action.isPending} onClick={()=>action.mutate({action:'assign',agentId:agent})}>Reassign</Button>{c.assigned_to&&<Button disabled={action.isPending} onClick={()=>action.mutate({action:'accept'})}><Check size={15} className="mr-1"/>Accept handoff</Button>}</>}
   {(pending||c.handoff_state==='HUMAN_ACTIVE')&&<Button variant="outline" disabled={action.isPending} onClick={()=>action.mutate({action:'resolve'})}>Resolve handoff</Button>}
   {c.handoff_state==='RESOLVED'&&<Button disabled={action.isPending} onClick={()=>action.mutate({action:'resume'})}>Resume AI</Button>}
  </div>
  {notifications.some(n=>['failed','unknown','sending'].includes(n.status))&&<p role="alert" className="mt-3 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">Notification needs review. Check delivery before reassigning. The request remains in this inbox.</p>}
  {pending&&!c.assigned_to&&<p className="mt-3 text-sm text-muted-foreground">No available team member. The request is safely queued.</p>}
  <details className="mt-4 text-xs text-muted-foreground"><summary className="cursor-pointer">Handoff history ({events.length})</summary><ol className="mt-2 space-y-2">{events.map(e=><li key={e.id} className="flex flex-wrap justify-between gap-2"><span className="capitalize">{e.event_type??'legacy'} → {stateLabel(e.to_state??'pending')}</span><time>{new Date(e.created_at).toLocaleString()}</time></li>)}</ol></details>
 </section>
}
export function HandoffWorkspace(){
 const client=useQueryClient(),[selected,setSelected]=useState(''),[name,setName]=useState(''),[area,setArea]=useState(''),[agent,setAgent]=useState('')
 const queue=useQuery({queryKey:['handoffs'],queryFn:()=>api<{data:Conversation[]}>(''),refetchInterval:10000})
 const routing=useQuery({queryKey:['handoff-routing'],queryFn:()=>api<{data:Rule[];teamMembers:Member[]}>('/routing')})
 const save=useMutation({mutationFn:()=>api('/routing','POST',{name,team_member_id:agent,areas:area.split(',').map(a=>a.trim()).filter(Boolean),priority:100,min_budget:0,max_budget:null,active:true}),onSuccess:()=>{setName('');setArea('');void client.invalidateQueries({queryKey:['handoff-routing']});toast.success('Routing rule saved')},onError:(e:Error)=>toast.error(e.message)})
 const availability=useMutation({mutationFn:(value:{member:Member;available:boolean;working_hours:Member['working_hours']})=>api('/team/'+value.member.id+'/availability','PATCH',{available:value.available,working_hours:value.working_hours??null}),onSuccess:()=>{void client.invalidateQueries({queryKey:['handoff-routing']});toast.success('Availability updated')},onError:(e:Error)=>toast.error(e.message)})
 const remove=useMutation({mutationFn:(id:string)=>api('/routing/'+id,'DELETE'),onSuccess:()=>void client.invalidateQueries({queryKey:['handoff-routing']}),onError:(e:Error)=>toast.error(e.message)})
 return <section className="mb-6 space-y-5" aria-label="Handoff workspace">
  <header className="rounded-2xl border bg-gradient-to-br from-slate-50 via-white to-teal-50 p-6 dark:from-slate-950 dark:via-slate-950 dark:to-teal-950"><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Team operations</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">A clear path from AI to your team</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Route requests, accept ownership and keep every transition visible. AI pauses once a handoff is accepted.</p></header>
  <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)]"><div className="rounded-2xl border bg-card p-5"><h3 className="font-medium">Handoff queue</h3>{queue.isLoading&&<p role="status">Loading queue…</p>}{queue.error&&<p role="alert">{queue.error.message}</p>}
   <div className="mt-3 max-h-80 space-y-2 overflow-y-auto pr-1">{queue.data?.data.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} aria-pressed={selected===c.id} className="flex w-full items-center gap-3 rounded-xl border p-3 text-start transition hover:bg-muted"><UserRound className="shrink-0 text-teal-600" size={18}/><span className="min-w-0"><span className="block truncate text-sm">Conversation {c.id.slice(0,8)}</span><span className="text-xs capitalize text-muted-foreground">{stateLabel(c.handoff_state)}</span></span></button>)}{queue.data?.data.length===0&&<p className="py-6 text-sm text-muted-foreground">All clear. New human requests will appear here.</p>}</div>
  </div><div>{selected?<HandoffControls key={selected} conversationId={selected}/>:<div className="flex min-h-48 items-center justify-center rounded-2xl border border-dashed p-6 text-center text-sm text-muted-foreground">Select a conversation to review ownership and history.</div>}</div></div>
  <div className="grid gap-5 lg:grid-cols-2"><section className="min-w-0 rounded-2xl border bg-card p-5"><h3 className="font-medium">Team availability</h3><p className="mt-1 text-xs text-muted-foreground">Only active, available members within their saved working hours receive assignments.</p>{routing.error&&<p role="alert">{routing.error.message}</p>}<div className="mt-4 space-y-4">{routing.data?.teamMembers.map(m=><div key={m.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm">{m.name}</p><p className="text-xs text-muted-foreground">{m.active?'Active':'Inactive'} · {m.working_hours?`${m.working_hours.start}–${m.working_hours.end} (${m.working_hours.timezone})`:'No hours restriction'}</p></div><Button size="sm" variant="outline" disabled={availability.isPending} aria-label={'Toggle availability for '+m.name} onClick={()=>availability.mutate({member:m,available:!m.available,working_hours:m.working_hours??null})}>{m.available?'Available':'Unavailable'}</Button></div><MemberSchedule key={m.id+JSON.stringify(m.working_hours)} member={m} busy={availability.isPending} onSave={value=>availability.mutate(value)}/></div>)}</div></section>
  <section className="rounded-2xl border bg-card p-5"><h3 className="font-medium">Area routing</h3><p className="mt-1 text-xs text-muted-foreground">Rules run in priority order, then use your default member or the least busy available member.</p><form onSubmit={e=>{e.preventDefault();save.mutate()}} className="mt-4 grid gap-3"><label className="text-xs">Rule name<input required maxLength={120} className="mt-1 block w-full rounded-lg border bg-background p-2 text-sm" value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-xs">Areas, separated by commas<input className="mt-1 block w-full rounded-lg border bg-background p-2 text-sm" value={area} onChange={e=>setArea(e.target.value)}/></label><label className="text-xs">Team member<select required className="mt-1 block w-full rounded-lg border bg-background p-2 text-sm" value={agent} onChange={e=>setAgent(e.target.value)}><option value="">Select member</option>{routing.data?.teamMembers.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><Button disabled={save.isPending||!agent}>Add routing rule</Button></form><ul className="mt-4 space-y-2">{routing.data?.data.map(r=><li key={r.id} className="flex items-center justify-between gap-3 rounded-lg bg-muted/50 p-3 text-sm"><span>{r.name}<span className="block text-xs text-muted-foreground">{r.areas.join(', ')||'All areas'}</span></span><Button size="sm" variant="ghost" disabled={remove.isPending} onClick={()=>remove.mutate(r.id)}>Remove</Button></li>)}</ul></section></div>
 </section>
}
