import {afterAll,afterEach,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest'
import {createClient} from '@supabase/supabase-js'
import {randomUUID} from 'node:crypto'
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs'
import {resolve} from 'node:path'
import {spawn,type ChildProcess} from 'node:child_process'
import {chromium,type Browser} from '@playwright/test'
import {Queue} from 'bullmq'
import pg from 'pg'
import {KnowledgeIngestion} from '../../backend/src/rag/KnowledgeIngestion'
import {MessageIdempotencyService} from '../../backend/src/whatsapp/MessageIdempotencyService'
import {OutboundMessageService} from '../../backend/src/whatsapp/OutboundMessageService'

const stack=JSON.parse(readFileSync(process.env.PHASE1_TEST_CONFIG!,'utf8'))
const admin=createClient(stack.url,stack.serviceKey,{auth:{persistSession:false,autoRefreshToken:false}})
const sql=new pg.Client({connectionString:stack.dbUrl})
const a=randomUUID(),b=randomUUID(),device=randomUUID(),bDevice=randomUUID(),sqlDevice=randomUUID(),kb=randomUUID()
const children=new Set<ChildProcess>(),logs:string[]=[],scenarios:Array<Record<string,unknown>>=[]
let token:string,bToken:string,next:ChildProcess,browser:Browser,frontendUrl:string,beforeB:unknown,checks=0,requests=0,externalRequests=0
const output=resolve(process.env.PHASE_RELIABILITY_REPORT_DIR??'docs/phase10/artifacts/reliability')
type Replica={child:ChildProcess;url:string;run:(command:string,input?:Record<string,unknown>)=>Promise<any>;kill:()=>Promise<void>}
let owner:Replica,peer:Replica,ownerFence:{ownerId:string;generation:number},afterTakeover:{ownerId:string;generation:number}
async function insert(table:string,data:unknown){const r=await admin.from(table).insert(data as any);if(r.error)throw r.error}
async function identity(name:string,org:string){const email=name+'@phase10.example.invalid',password='Local-reliability-fixture-123!';const c=await admin.auth.admin.createUser({email,password,email_confirm:true,app_metadata:{org_id:b}});if(c.error)throw c.error;await insert('users',{id:c.data.user.id,org_id:org,email,name,active:true,role:'admin',password_hash:'fixture'});const client=createClient(stack.url,stack.anonKey,{auth:{persistSession:false}});const s=await client.auth.signInWithPassword({email,password});if(s.error)throw s.error;return s.data.session!.access_token}
async function snapshotB(){const tables=(await sql.query("select table_name from information_schema.columns where table_schema='public' and column_name='org_id' order by table_name")).rows as Array<{table_name:string}>;const result:Record<string,unknown>={};for(const {table_name} of tables){result[table_name]=(await sql.query('select to_jsonb(t) row from public."'+table_name+'" t where org_id=$1 order by to_jsonb(t)::text',[b])).rows}result.organizations=(await sql.query('select to_jsonb(t) row from organizations t where id=$1',[b])).rows;result.contact_memory=(await sql.query('select to_jsonb(t) row from contact_memory t join contacts c on c.id=t.contact_id where c.org_id=$1 order by to_jsonb(t)::text',[b])).rows;return result}
async function until<T>(get:()=>Promise<T>,test:(value:T)=>boolean,timeout=15000){const start=Date.now();for(;;){const value=await get();if(test(value))return value;if(Date.now()-start>timeout)throw new Error('Condition timeout');await new Promise(r=>setTimeout(r,100))}}
async function replica(name:string,redis=true,redisPort=stack.redisPort):Promise<Replica>{
 const env={...process.env,REPLICA_NAME:name,REPLICA_DEVICE:device,REPLICA_ORG:a,REDIS_HOST:redis?'127.0.0.1':'',REDIS_PORT:String(redisPort)}
 const child=spawn(process.execPath,['--import','tsx',resolve('tests/fixtures/device-replica.ts')],{cwd:resolve('.'),env,stdio:['ignore','pipe','pipe','ipc'],windowsHide:true});children.add(child)
 const pending=new Map<string,{done:(v:any)=>void;reject:(e:Error)=>void;timer:NodeJS.Timeout}>();let ready:(url:string)=>void,fail:(e:Error)=>void
 const startup=new Promise<string>((done,reject)=>{ready=done;fail=reject})
 child.stdout!.on('data',c=>logs.push(c.toString()));child.stderr!.on('data',c=>logs.push(c.toString()))
 child.on('message',(m:any)=>{if(m.kind==='ready')ready(m.url);if(m.kind==='done'){const p=pending.get(m.id);if(p){clearTimeout(p.timer);pending.delete(m.id);if(m.error)p.reject(new Error(m.error));else p.done(m.result)}}})
 child.on('exit',code=>{children.delete(child);fail(new Error('Replica exit '+code+' '+logs.slice(-3).join(' ').slice(-2000)));for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error('Replica exit '+code))}pending.clear()})
 const url=await Promise.race([startup,new Promise<never>((_,reject)=>{const timer=setTimeout(()=>reject(new Error('Replica startup timeout')),30000);timer.unref();startup.finally(()=>clearTimeout(timer)).catch(()=>undefined)})])
 return{child,url,run:(command,input={})=>new Promise((done,reject)=>{const id=randomUUID(),timer=setTimeout(()=>{pending.delete(id);reject(new Error('Replica command timeout '+command))},30000);pending.set(id,{done,reject,timer});child.send({id,command,...input})}),kill:()=>new Promise(done=>{if(child.exitCode!==null||child.signalCode!==null)return done();child.once('exit',()=>done());child.kill('SIGKILL')})}
}
const params=(action:string,ownerId=randomUUID(),generation:number|null=null,dev=sqlDevice,org=a,ttl=2)=>({p_org:org,p_device:dev,p_owner:ownerId,p_generation:generation,p_action:action,p_ttl:ttl})
async function rpc(name:string,input:Record<string,unknown>){return admin.rpc(name,input)}
async function queued(waId:string=randomUUID(),dev=device,org=a){const result=await rpc('enqueue_device_send',{p_org:org,p_device:dev,p_id:randomUUID(),p_wa_id:waId,p_jid:'971500001111@s.whatsapp.net',p_text:'Verified relay response'});if(result.error)throw result.error;return result.data}
async function physical(waId:string){return Number((await sql.query('select count(*) n from phase10_test_physical_sends where device_id=$1 and wa_id=$2',[device,waId])).rows[0].n)}
async function http(surface:string,path:string,method='GET',body?:unknown,credential=token){requests++;const response=await fetch((surface==='backend'?owner.url+'/api/v1':frontendUrl+'/api')+path,{method,headers:{authorization:'Bearer '+credential,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return{status:response.status,body:await response.json()}}
beforeAll(async()=>{
 mkdirSync(output,{recursive:true})
 const native=globalThis.fetch;vi.stubGlobal('fetch',(input:string|URL|Request,init?:RequestInit)=>{const url=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url);if(!['127.0.0.1','localhost'].includes(url.hostname)){externalRequests++;throw Error('External request blocked')}return native(input,init)})
 await sql.connect();await sql.query('create table phase10_test_physical_sends(org_id uuid,device_id uuid,wa_id text,owner_id uuid,generation bigint,replica text,jid text,content text);create table phase10_test_embedding_calls(replica text,chunk_count int);revoke all on phase10_test_physical_sends,phase10_test_embedding_calls from public,anon,authenticated;alter table phase10_test_physical_sends enable row level security;alter table phase10_test_embedding_calls enable row level security')
 await insert('organizations',[{id:a,name:'Reliability A',slug:'phase10-a'},{id:b,name:'Private Reliability B',slug:'phase10-b'}]);await insert('devices',[{id:device,org_id:a,name:'Replica device'},{id:sqlDevice,org_id:a,name:'SQL fence device'},{id:bDevice,org_id:b,name:'Private B device'}]);await insert('knowledge_bases',{id:kb,org_id:a,name:'Queued knowledge'})
 token=await identity('runtime-a',a);bToken=await identity('runtime-b',b)
 await rpc('device_runtime_lease',params('acquire',randomUUID(),null,bDevice,b,120));await queued('PRIVATE-B-JOB',bDevice,b)
 owner=await replica('A');peer=await replica('B');await owner.run('connect');await until(()=>owner.run('snapshot'),v=>v.snapshot?.connected===true);ownerFence=(await owner.run('snapshot')).fence
 next=spawn(process.execPath,[resolve('node_modules/next/dist/bin/next'),'start','-p','0','-H','127.0.0.1'],{cwd:resolve('frontend'),env:{...process.env,NODE_ENV:'production',BACKEND_URL:owner.url},stdio:['ignore','pipe','pipe'],windowsHide:true});children.add(next)
 await new Promise<void>((done,reject)=>{const timer=setTimeout(()=>reject(Error('Next startup timeout')),60000);const read=(c:Buffer)=>{const t=c.toString();logs.push(t);const m=t.match(/http:\/\/127\.0\.0\.1:\d+/);if(m)frontendUrl=m[0];if(/Ready in/.test(t)){clearTimeout(timer);done()}};next.stdout!.on('data',read);next.stderr!.on('data',read);next.on('exit',code=>{clearTimeout(timer);reject(Error('Next exit '+code))})})
 browser=await chromium.launch({headless:true});mkdirSync(output,{recursive:true})
})
beforeEach(async()=>{beforeB=await snapshotB()})
afterEach(async context=>{expect(await snapshotB()).toEqual(beforeB);checks++;scenarios.push({name:context.task.name,tenantBUnchanged:true})})
afterAll(async()=>{
 for(const child of children){if(child.exitCode===null&&child.signalCode===null){const exited=new Promise<void>(done=>child.once('exit',()=>done()));child.kill('SIGKILL');await exited}}children.clear()
 await browser?.close();await sql.end();vi.unstubAllGlobals()
 writeFileSync(resolve(stack.directory,'reliability-http-evidence.json'),JSON.stringify({requests,tenantBSnapshotChecks:checks,externalRequests,transport:'local stub; real gateway, leases, encryption, Redis, Auth and REST',scenarios,appliedToLiveProject:false},null,2))
 writeFileSync(resolve(output,'runtime-scenarios.json'),JSON.stringify({ownerFence,afterTakeover,scenarios,externalRequests},null,2))
})
describe.each(['backend','frontend'])('%s authenticated device boundary',surface=>{
 it('reads the own device despite forged organization query',async()=>{const r=await http(surface,'/devices/'+device+'/qr?org_id='+b+'&orgId='+b);expect(r.status).toBe(200);expect(r.body.data.id).toBe(device)})
 it('rejects foreign read',async()=>expect((await http(surface,'/devices/'+bDevice+'/qr')).status).toBe(404))
 it('rejects foreign connect with a forged body',async()=>expect((await http(surface,'/devices/'+bDevice+'/connect','POST',{org_id:b,orgId:b})).status).toBe(404))
 it('rejects foreign disconnect',async()=>expect((await http(surface,'/devices/'+bDevice+'/disconnect','POST')).status).toBe(404))
 it('rejects foreign delete',async()=>expect((await http(surface,'/devices/'+bDevice,'DELETE')).status).toBe(404))
 it('rejects cross-tenant credentials for own device',async()=>expect((await http(surface,'/devices/'+device+'/connect','POST',{},bToken)).status).toBe(404))
 it('requires authentication',async()=>expect((await http(surface,'/devices/'+device+'/qr','GET',undefined,'invalid-token')).status).toBe(401))
})
it('a second API replica returns a controlled conflict without clearing owner credentials',async()=>{
 await owner.run('write-auth');const response=await fetch(peer.url+'/api/v1/devices/'+device+'/connect',{method:'POST',headers:{authorization:'Bearer '+token}});requests++;expect(response.status).toBe(409);expect((await response.json()).code).toBe('DEVICE_LEASE_HELD');expect((await owner.run('snapshot')).fence).toEqual(ownerFence)
})
it('encrypts credentials and preserves Buffer roundtrip under ownership',async()=>{const result=await owner.run('write-auth');expect(result.token).toBe('LOCAL_ONLY_SECRET');const rows=(await sql.query("select data from baileys_sessions where device_id=$1 and key_type='test'",[device])).rows;expect(rows).toHaveLength(1);expect(rows[0].data).not.toContain('LOCAL_ONLY_SECRET');expect(result.bytes.data??result.bytes).toEqual([1,2,3])})
it('browser displays the authenticated device workspace without application errors',async()=>{const context=await browser.newContext();await context.addCookies([{name:'sb-access-token',value:token,url:frontendUrl,httpOnly:true}]);const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(frontendUrl+'/devices');await expect.poll(()=>page.locator('body').innerText()).toContain('Replica device');expect(errors).toEqual([]);await page.screenshot({path:resolve(output,'device-runtime-desktop.png'),fullPage:true});await context.close()})
it('concurrent first acquisitions admit exactly one owner',async()=>{const owners=[randomUUID(),randomUUID()];const results=await Promise.all(owners.map(id=>rpc('device_runtime_lease',params('acquire',id))));expect(results.filter(r=>r.data)).toHaveLength(1);expect(results.every(r=>!r.error)).toBe(true);await rpc('device_runtime_lease',params('revoke'))})
it('reacquisition advances generation and old renew cannot resurrect it',async()=>{const first=await rpc('device_runtime_lease',params('acquire'));expect(first.error).toBeNull();await rpc('device_runtime_lease',params('release',first.data.owner_id,first.data.generation));const second=await rpc('device_runtime_lease',params('acquire'));expect(second.data.generation).toBeGreaterThan(first.data.generation);expect((await rpc('device_runtime_lease',params('renew',first.data.owner_id,first.data.generation))).error?.code).toBe('PT409');await rpc('device_runtime_lease',params('revoke'))})
it('an expired lease cannot renew even if no successor exists',async()=>{const first=await rpc('device_runtime_lease',params('acquire'));await sql.query("update device_runtime_leases set lease_until=clock_timestamp()-interval '1 second' where device_id=$1",[sqlDevice]);expect((await rpc('device_runtime_lease',params('renew',first.data.owner_id,first.data.generation))).error?.code).toBe('PT409');await rpc('device_runtime_lease',params('revoke'))})
it('foreign organization cannot acquire or revoke a device',async()=>{for(const action of ['acquire','revoke'])expect((await rpc('device_runtime_lease',params(action,randomUUID(),null,bDevice,a))).error?.code).toBe('PT404')})
it('foreign parent links are rejected for private tables',async()=>{expect((await admin.from('device_runtime_leases').insert({device_id:randomUUID(),org_id:a,owner_id:randomUUID(),generation:1,lease_until:new Date().toISOString()})).error?.code).toBe('PT404');expect((await admin.from('device_outbound_jobs').insert({id:randomUUID(),org_id:a,device_id:bDevice,wa_message_id:'FORGED',jid:'x',content:'x'})).error?.code).toBe('PT404')})
it('stale generations cannot update state, credentials or claim sends',async()=>{const job=await queued('STALE-CLAIM');for(const [name,args] of [['fenced_device_state',{p_status:'disconnected'}],['fenced_session_write',{p_action:'clear'}],['claim_device_send',{p_id:job.id}]] as const){expect((await rpc(name,{p_org:a,p_device:device,p_owner:ownerFence.ownerId,p_generation:ownerFence.generation-1,...args})).error?.code).toBe('PT409')}})
it('unfenced auth mutation cannot clear an active owner',async()=>expect((await rpc('fenced_session_write',{p_org:a,p_device:device,p_owner:null,p_generation:null,p_action:'clear'})).error?.code).toBe('PT409'))
it('authenticated and anonymous REST cannot read leases, jobs or execute lease RPCs',async()=>{for(const credential of [token,bToken,stack.anonKey]){const client=createClient(stack.url,stack.anonKey,{auth:{persistSession:false},global:{headers:{authorization:'Bearer '+credential}}});for(const table of ['device_runtime_leases','device_outbound_jobs'])expect((await client.from(table).select('*')).error?.code).toBe('42501');expect((await client.rpc('device_runtime_lease',params('acquire'))).error?.code).toBe('42501')}})
it('a non-owner relays through the actual owner exactly once',async()=>{const id=randomUUID();const receipt=await peer.run('send',{input:{messageId:id}});expect(receipt.messageId).toBe(id);expect(await physical(id)).toBe(1);const repeat=await peer.run('send',{input:{messageId:id}});expect(repeat.messageId).toBe(id);expect(await physical(id)).toBe(1)})
it('notifications without preferred device select only a tenant-owned relay',async()=>{const result=await peer.run('send',{input:{deviceId:null}});expect(result.deviceId).toBe(device);expect(await physical(result.messageId)).toBe(1)})
it('competing notifications claim one physical send and queue stores IDs only',async()=>{const id=randomUUID(),job=await queued(id);const queue=new Queue('device-send-'+device,{connection:{host:'127.0.0.1',port:stack.redisPort}});await queue.add('send',{orgId:a,deviceId:device,requestId:job.id},{jobId:job.id});const stored=await queue.getJob(job.id);expect(stored?.data).toEqual({orgId:a,deviceId:device,requestId:job.id});await queue.close();await until(()=>physical(id),n=>n===1);await new Promise(r=>setTimeout(r,500));expect(await physical(id)).toBe(1)})
it('expired queued requests are cancelled without any transport call',async()=>{const id=randomUUID(),job=await queued(id);await sql.query("update device_outbound_jobs set deadline=clock_timestamp()-interval '1 second' where id=$1",[job.id]);await until(async()=>(await admin.from('device_outbound_jobs').select('state').eq('id',job.id).single()).data?.state,v=>v==='cancelled');expect(await physical(id)).toBe(0)})
it('conflicting send identities are rejected without another row',async()=>{const id=randomUUID();await queued(id);expect((await rpc('enqueue_device_send',{p_org:a,p_device:device,p_id:randomUUID(),p_wa_id:id,p_jid:'other@s.whatsapp.net',p_text:'changed'})).error?.code).toBe('PT409');expect((await admin.from('device_outbound_jobs').select('id').eq('device_id',device).eq('wa_message_id',id)).data).toHaveLength(1)})
it('lost acknowledgement enters review and cannot be automatically resent',async()=>{await owner.run('mode',{mode:'unknown'});const id=randomUUID(),job=await queued(id);await until(async()=>(await admin.from('device_outbound_jobs').select('state').eq('id',job.id).single()).data?.state,v=>v==='review_required');expect(await physical(id)).toBe(1);const claim=await rpc('claim_device_send',{p_org:a,p_device:device,p_id:job.id,p_owner:ownerFence.ownerId,p_generation:ownerFence.generation});expect(claim.data).toBeNull();expect(await physical(id)).toBe(1);await owner.run('mode',{mode:'normal'})})
it('two embedding replicas process one version with one provider call',async()=>{const ingestion=new KnowledgeIngestion(admin),version=await ingestion.enqueue(a,kb,'queued.txt',Buffer.from('Verified queued knowledge.'));await Promise.all([owner.run('index',{versionId:version.versionId}),peer.run('index',{versionId:version.versionId})]);await until(async()=>(await admin.from('knowledge_document_versions').select('status,attempts').eq('id',version.versionId).single()).data,v=>v?.status==='ready');expect((await admin.from('knowledge_document_versions').select('attempts,chunk_count').eq('id',version.versionId).single()).data).toMatchObject({attempts:1,chunk_count:1});expect(Number((await sql.query('select count(*) n from phase10_test_embedding_calls')).rows[0].n)).toBe(1)})
it('completed indexing notification can be recreated after parsing lease expires',async()=>{const ingestion=new KnowledgeIngestion(admin),version=await ingestion.enqueue(a,kb,'recovery.txt',Buffer.from('Recovered knowledge after abandoned parsing.'));const claim=await rpc('claim_knowledge_version',{p_org:a,p_version:version.versionId,p_token:randomUUID()});expect(claim.data).toBeTruthy();await peer.run('index-notification',{versionId:version.versionId});const queue=new Queue('document-indexing',{connection:{host:'127.0.0.1',port:stack.redisPort}});await until(async()=>(await queue.getJob(version.versionId))?.getState(),v=>v==='completed');await sql.query("update knowledge_document_versions set lease_until=clock_timestamp()-interval '1 second' where id=$1",[version.versionId]);await peer.run('index',{versionId:version.versionId});await until(async()=>(await admin.from('knowledge_document_versions').select('status').eq('id',version.versionId).single()).data?.status,v=>v==='ready');await queue.close();expect((await admin.from('knowledge_document_versions').select('attempts').eq('id',version.versionId).single()).data?.attempts).toBe(2)})
it('unavailable Redis fails publication promptly, preserves work and shuts down cleanly',async()=>{const down=await replica('Redis-unavailable',true,1),version=await new KnowledgeIngestion(admin).enqueue(a,kb,'redis-down.txt',Buffer.from('Durable work survives unavailable Redis.'));const started=Date.now();expect(await down.run('index',{versionId:version.versionId})).toBe(false);expect(Date.now()-started).toBeLessThan(5000);await down.run('recover-index');expect((await admin.from('knowledge_document_versions').select('status').eq('id',version.versionId).single()).data?.status).toBe('ready');const stopping=Date.now();await down.run('shutdown');expect(Date.now()-stopping).toBeLessThan(8000)})
it('database receipt validation quarantines a mismatched acknowledgement',async()=>{const first=await rpc('device_runtime_lease',params('acquire')),job=await queued('MISMATCHED-RECEIPT',sqlDevice);const p={p_org:a,p_device:sqlDevice,p_id:job.id,p_owner:first.data.owner_id,p_generation:first.data.generation};expect((await rpc('claim_device_send',p)).data).toBeTruthy();expect((await rpc('finish_device_send',{...p,p_receipt:'DIFFERENT',p_success:true})).error).toBeNull();expect((await admin.from('device_outbound_jobs').select('state').eq('id',job.id).single()).data?.state).toBe('review_required');await rpc('device_runtime_lease',params('revoke'))})
it('paused owner stops sending and successor advances generation',async()=>{const id=randomUUID();const stale=owner.run('freeze',{ms:4200,waId:id});await new Promise(r=>setTimeout(r,2200));await peer.run('connect');await until(()=>peer.run('snapshot'),v=>v.snapshot?.connected);afterTakeover=(await peer.run('snapshot')).fence;expect(afterTakeover.generation).toBeGreaterThan(ownerFence.generation);await expect(stale).rejects.toThrow();expect(await physical(id)).toBe(0);expect((await owner.run('snapshot')).snapshot?.connected??false).toBe(false);const active=await sql.query('select count(*)::int n from device_runtime_leases where device_id=$1 and lease_until>clock_timestamp() and owner_id is not null',[device]);expect(active.rows[0].n).toBe(1)})
it('a stale worker cannot send after takeover',async()=>{const id=randomUUID(),job=await queued(id);await expect(owner.run('process-stale',{...ownerFence,requestId:job.id})).rejects.toThrow('DEVICE_LEASE_LOST');await until(()=>physical(id),n=>n===1);expect(await physical(id)).toBe(1)})
it('owner crash triggers bootstrap takeover and saved AI reply sends once',async()=>{
 await next.kill();children.delete(next);await owner.kill();await peer.kill()
 await new Promise(r=>setTimeout(r,2200));owner=await replica('Crash-owner');await owner.run('connect');await until(()=>owner.run('snapshot'),v=>v.snapshot?.connected)
 const persistence=new MessageIdempotencyService(admin),inbound=await persistence.receive({orgId:a,deviceId:device,waMessageId:randomUUID(),jid:'971500001111@s.whatsapp.net',phone:'971500001111',content:'Saved answer requested',type:'text'}),claim=await persistence.claim(inbound)
 const outbound=await new OutboundMessageService(admin,async()=>{throw Error('No pre-crash send')}).prepare(inbound,claim!,'Verified saved answer')
 await owner.kill();peer=await replica('Takeover-no-Redis',false);await peer.run('bootstrap');await until(()=>peer.run('snapshot'),v=>v.snapshot?.connected,15000);await until(()=>physical(outbound.wa_message_id),n=>n===1);await new Promise(r=>setTimeout(r,1000));expect(await physical(outbound.wa_message_id)).toBe(1);expect((await admin.from('messages').select('processing_status').eq('id',outbound.id).single()).data?.processing_status).toBe('completed')
})
it('database owner polling drains queued sends when Redis is absent',async()=>{const id=randomUUID();await queued(id);await until(()=>physical(id),n=>n===1);expect(await physical(id)).toBe(1)})
it('graceful shutdown releases ownership while preserving reconnect status',async()=>{const first=(await peer.run('snapshot')).fence;await peer.run('shutdown');const lease=(await admin.from('device_runtime_leases').select('*').eq('device_id',device).single()).data;expect(lease.owner_id).toBeNull();expect((await admin.from('devices').select('status').eq('id',device).single()).data?.status).toBe('connected');owner=await replica('After-graceful');await owner.run('bootstrap');await until(()=>owner.run('snapshot'),v=>v.snapshot?.connected);expect((await owner.run('snapshot')).fence.generation).toBeGreaterThan(first.generation)})
it('crash after physical delivery leaves an uncertain send quarantined across takeover',async()=>{await owner.run('mode',{mode:'crash-after-send'});const id=randomUUID(),job=await queued(id);await until(()=>physical(id),n=>n===1);await until(async()=>owner.child.exitCode,v=>v!==null);peer=await replica('After-uncertain-crash');await peer.run('bootstrap');await until(()=>peer.run('snapshot'),v=>v.snapshot?.connected,15000);await new Promise(r=>setTimeout(r,1000));expect(await physical(id)).toBe(1);expect((await admin.from('device_outbound_jobs').select('state').eq('id',job.id).single()).data?.state).toBe('sending')})
it('an operator on another replica revokes ownership without clearing credentials remotely',async()=>{const operator=await replica('Operator',false);const r=await fetch(operator.url+'/api/v1/devices/'+device+'/disconnect',{method:'POST',headers:{authorization:'Bearer '+token}});requests++;expect(r.status).toBe(200);await until(()=>peer.run('snapshot'),v=>!v.snapshot?.connected);expect((await admin.from('devices').select('status').eq('id',device).single()).data?.status).toBe('disconnected');await operator.run('shutdown')})
