// GROUND TRUTH - these values are never generated by Claude.
// They are injected directly into prompts and direct reply messages.

/** Historical reference only. Runtime company facts are resolved by RuntimeConfigResolver.
 * This object must never be used as a default for an organization. */
export const COMPANY = {
  name: 'Investment Experts Real Estate',
  short: 'IERE',
  owner: 'Muhammad Imran Khan',
  phone: '+971 50 221 3802',
  email: 'hello@investmentexperts.ae',
  website: 'https://www.investmentexperts.ae',
  address: 'Concord Tower, Dubai Media City, Dubai',
  maps: 'https://maps.app.goo.gl/iBGGbKJzhfMExrmA6',
  hours: 'Monday to Saturday, 9:00 AM - 7:00 PM (Dubai time)',
  about:
    '15+ years of Dubai real estate expertise. 500+ properties sold. AED 2B+ in transactions. Specialists in luxury, off-plan, and investment properties across 32+ Dubai communities.',
} as const

export const TEAM = [
  {
    id: 'imran',
    name: 'Muhammad Imran Khan',
    role: 'CEO',
    phone: '+971 50 221 3802',
    wa: '971502213802',
    areas: [] as string[],
    minBudget: 5_000_000,
    isDefault: false,
    isClientFacing: true,
    dept: 'leadership',
  },
  {
    id: 'hammad',
    name: 'Hammad Khan',
    role: 'Sales Manager',
    phone: '+971 55 229 2910',
    wa: '971552292910',
    areas: ['all'] as string[],
    minBudget: 0,
    isDefault: true,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'waheed',
    name: 'Waheed Uz Zaman',
    role: 'Property Consultant',
    phone: '+971 55 982 1786',
    wa: '971559821786',
    areas: ['Dubai Marina', 'Arjan', 'Dubai Sports City', 'Motor City', 'DSC'],
    minBudget: 0,
    isDefault: false,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'laiba',
    name: 'Laiba Shahzad',
    role: 'Property Consultant',
    phone: '+971 55 228 5188',
    wa: '971552285188',
    areas: ['Jumeirah Village Circle', 'JVC', 'Jumeirah Lake Towers', 'JLT', 'Majan', 'Al Zorah', 'DLRC'],
    minBudget: 0,
    isDefault: false,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'sarosh',
    name: 'Sarosh Iqbal',
    role: 'Property Consultant',
    phone: '+971 55 789 1207',
    wa: '971557891207',
    areas: ['Business Bay', 'Downtown Dubai', 'DIFC'],
    minBudget: 0,
    isDefault: false,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'anushka',
    name: 'Anushka Lalwani',
    role: 'Property Consultant',
    phone: null,
    wa: null,
    areas: [] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'asif',
    name: 'Muhammad Asif Malik',
    role: 'Property Consultant',
    phone: '+971 58 822 4640',
    wa: '971588224640',
    areas: [] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'tanzeel',
    name: 'Tanzeel Uz Zaman',
    role: 'Property Consultant',
    phone: '+971 52 958 3328',
    wa: '971529583328',
    areas: [] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'sarah',
    name: 'Sarah Shaheen',
    role: 'Marketing Manager',
    phone: null,
    wa: null,
    areas: [] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: false,
    dept: 'marketing',
  },
  {
    id: 'sumbul',
    name: 'Sumbul',
    role: 'Sales Team',
    phone: '+92 315 848 0330',
    wa: '923158480330',
    areas: ['all'] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'muniq',
    name: 'Muniq Malik',
    role: 'Property Consultant',
    phone: '+971 52 799 2280',
    wa: '971527992280',
    areas: ['all'] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'sharmeen',
    name: 'Sharmeen',
    role: 'Property Consultant',
    phone: '+971 56 916 906',
    wa: '97156916906',
    areas: ['all'] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: true,
    dept: 'sales',
  },
  {
    id: 'aya',
    name: 'Aya',
    role: 'HR',
    phone: null,
    wa: null,
    areas: [] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: false,
    dept: 'hr',
  },
  {
    id: 'ayaz',
    name: 'Ayaz Khan',
    role: 'Technical Director',
    phone: null,
    wa: null,
    areas: [] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: false,
    dept: 'technical',
  },
  {
    id: 'hrithik',
    name: 'Hrithik Bharadwaj',
    role: 'Technical Support',
    phone: null,
    wa: null,
    areas: [] as string[],
    minBudget: 0,
    isDefault: false,
    isClientFacing: false,
    dept: 'technical',
  },
] as const

export type TeamMember = (typeof TEAM)[number]

const INTERNAL_IDS = new Set(['ayaz', 'hrithik', 'sarah', 'aya'])

export function isInternalStaff(nameOrId: string): boolean {
  const n = nameOrId.toLowerCase().trim()
  return (
    INTERNAL_IDS.has(n) ||
    n.includes('ayaz') ||
    n.includes('hrithik') ||
    n.includes('sarah shaheen') ||
    (TEAM as unknown as TeamMember[]).some(
      (member) => !member.isClientFacing && member.name.toLowerCase().includes(n),
    )
  )
}

export function getClientFacingTeam(): TeamMember[] {
  return (TEAM as unknown as TeamMember[]).filter((member) => member.isClientFacing)
}

export function hasUsableContact(member: TeamMember): boolean {
  if (!member.isClientFacing) return false
  if (!member.phone || !member.wa) return false
  if (/[xX]{2,}/.test(member.phone) || /[xX]{2,}/.test(member.wa)) return false
  return true
}

export function findAgentByName(hint: string): TeamMember | undefined {
  const normalizedHint = hint.toLowerCase()
  return (TEAM as unknown as TeamMember[]).find(
    (member) => member.isClientFacing === true && member.name.toLowerCase().includes(normalizedHint),
  )
}

export function findBestAgent(area?: string, budget?: number): TeamMember {
  const team = getClientFacingTeam()
  const reachable = team.filter(hasUsableContact)
  const pool = reachable.length > 0 ? reachable : team

  if (budget && budget >= 5_000_000) {
    return pool.find((member) => member.id === 'imran') ?? pool.find((member) => member.isDefault) ?? pool[0]
  }

  if (area) {
    const normalizedArea = area.toLowerCase()
    const match = pool.find(
      (member) =>
        Array.isArray(member.areas) &&
        member.areas.length > 0 &&
        member.areas.some(
          (zone) => zone.toLowerCase().includes(normalizedArea) || normalizedArea.includes(zone.toLowerCase()),
        ),
    )
    if (match) return match
  }

  return pool.find((member) => member.isDefault && hasUsableContact(member)) ?? pool[0]
}

export function agentCard(agent: TeamMember, lang: 'en' | 'ar'): string {
  if (!hasUsableContact(agent)) {
    const ceo = (TEAM as unknown as TeamMember[]).find((member) => member.id === 'imran')
    if (ceo && hasUsableContact(ceo)) return agentCard(ceo, lang)
    return ''
  }

  const wa = `https://wa.me/${agent.wa}`
  if (lang === 'ar') {
    return `━━━━━━━━━━━━━━━━━━\n👤 *${agent.name}*\n🏷 ${agent.role}\n📞 ${agent.phone}\n💬 واتساب: ${wa}\n━━━━━━━━━━━━━━━━━━`
  }
  return `━━━━━━━━━━━━━━━━━━\n👤 *${agent.name}*\n🏷 ${agent.role}\n📞 ${agent.phone}\n💬 WhatsApp: ${wa}\n━━━━━━━━━━━━━━━━━━`
}
